### ISSUE TITLE
Rails 5: stored image is deleted when updating a record

### ISSUE THREAD

**Issue by jmuheim** [lebedev-yury/carrierwave-base64#51] opened 2017-02-13 17:23 UTC
When an image was uploaded to a record using `base64_mount_uploader`, and the record is updated, the stored image is deleted.

I have noticed this bug after upgrading an existing Rails application from 4.2.7 to 5.0.1.

I have created a working demo:

https://github.com/jmuheim/test-rails5-base64-carrierwave

Just run it and do the following to replicate:

- Go to http://localhost:3000/users/new
- Create a new user with a name and an avatar (copy the base64 string in the disabled textarea (`data:image/png...` and paste it into the "Avatar" field)
- Hit "Create User"
- Now you should see the user with the uploaded image:  
  ![image](https://cloud.githubusercontent.com/assets/1814983/22894336/f6b813ea-f218-11e6-8bec-122ece95813e.png)
- Now click "Edit"
- Click "Update User"
- Now the image has disappeared:  
  ![image](https://cloud.githubusercontent.com/assets/1814983/22894384/19be22e4-f219-11e6-990b-576fb2956d03.png)

The commit that introduces the bug is this one: https://github.com/jmuheim/test-rails5-base64-carrierwave/commit/9d2f65a8d87b03c3d94768da9069bf8e50d0b13b. It's only adding the carrierwave-base64 gem, changing 'mount_uploader' to 'mount_base64_uploader', and changing the upload field to a textarea (and providing the copy&paste string in a disabled textarea)

We are using your gem in our application on a daily base, and it's a very harmful bug to us right now. How can I help you to fix this bug as fast as possible?

Thank you for this very useful gem.

**Comment by jmuheim** [comment] 2017-02-13 17:28
By the way, as my application is in production with this bug, I have created a workaround like this:

```erb
    <% if f.object.avatar.file.nil? %>
      <%= f.label :avatar %>
      <%= f.text_area :avatar %>
    <% end %>
```

This way the image can't be changed when updating the record, and it is not removed by accident (by the bug). If the user indeed wants to change the avatar, he can remove it using the `<%= f.check_box :remove_avatar %>` checkbox, and then upload a new avatar.

This prevents the biggest harms. But we need a fix for this soon.

**Comment by lebedev-yury** [comment] 2017-02-14 08:06
@jmuheim thanks for reporting! Will work on a fix soon

**Comment by jmuheim** [comment] 2017-02-14 10:02
Thank you.

**Comment by jmuheim** [comment] 2017-02-23 17:14
Any news on this issue?

**Comment by lebedev-yury** [comment] 2017-02-23 17:39
@jmuheim sorry, was a bit busy. Will try to get my hands on it next couple of days

**Comment by jmuheim** [comment] 2017-03-17 10:38
Any news? I think I could fix this on my side by simply checking in the controller whether a base64 string is sent by the form, or only a file path string, and only assign the form value when it's a base64 string.

But as it has worked before without this check, I guess there is potential for optimisation within the gem itself.

**Comment by lebedev-yury** [comment] 2017-03-17 18:30
Ok, so I found the issue at least. It seems that the file gets deleted, since the input field for a base64 string is filled with a filename (which isn't a base64 string, and therefor get's rejected.

I will fix that in a moment

**Comment by lebedev-yury** [comment] 2017-03-17 19:28
@jmuheim The issue is fixed in version 2.5.0.

Sorry it took a while, I'm getting used to be a father now ;)

**Closed** 2017-03-17 19:27 UTC

**Comment by lebedev-yury** [comment] 2017-03-17 19:31
@jmuheim and thank you for a great bug report, it's pleasure to work with

**Comment by jmuheim** [comment] 2017-03-17 19:40
Congratulations to being a father now, Yuri! :)

I will update the gem soon and will give you info whether it works for me.

**Comment by lebedev-yury** [comment] 2017-03-18 10:43
Thank you!

**Comment by jmuheim** [comment] 2017-03-20 10:09
It works! Thank you! :-)

> and thank you for a great bug report, it's pleasure to work with

This is the spirit of great open source! 👍

**Comment by jmuheim** [comment] 2017-03-21 20:29
Just one little side note: since I updated the gem, `File.basename(@finding.screenshot.to_s)` doesn't result in `file.png` anymore, but in `screenshot.png`. It's no problem for my application, I'm just wondering whether this is by intention or maybe some new behaviour that "slipped in"?

**Comment by lebedev-yury** [comment] 2017-03-22 08:18
@jmuheim It's actually a change, introduced in 2.4: https://github.com/lebedev-yury/carrierwave-base64/commit/91e11a954a0222a445e0e9888d4ac2215068ab82#diff-299f76b2e8ac002765221bbaefdd9849R17

The default file name is now taken from the attribute name (this should have been documented in the changelog)

**Comment by jmuheim** [comment] 2017-03-22 08:20
Ok I thought that this could be the case. Just wanted to make sure...

Thanks for responding.

**Comment by skatezar** [comment] 2021-03-22 18:37
Hi - I am currently experiencing the same bug - could you please clarify how exactly you solved it; aka what I need to do to fix it on my project? lg

**Comment by celsoMartins** [comment] 2022-09-07 17:23
It is still happening here too. Every update operation in the controller removes the image that should be sent to Cloudinary. I was able to contingency It by adding a callback inside the model to update the required field before saving.
