### ISSUE TITLE
Undefined Method `strip` for File

### ISSUE THREAD

**Issue by Copywright** [lebedev-yury/carrierwave-base64#36] opened 2016-06-20 14:15 UTC
NoMethodError: undefined method `'strip' for #<File:0x007fb46a392328>
/Users/herbert/.rvm/gems/ruby-2.3.1/gems/carrierwave-base64-2.3.0/lib/carrierwave/base64/adapter.rb:14:in block in mount_base64_uploader'`

I'm 'uploading' a local file in my seeds.rb in Rails 4. Get this error after bundle updating.

**Comment by lebedev-yury** [comment] 2016-06-20 14:21
@Copywright thanks for reporting! Which version are you using currently?

**Comment by Copywright** [comment] 2016-06-20 14:45
Using 2.3.0

**Comment by lebedev-yury** [comment] 2016-06-20 14:59
thanks, i will fix that problem today, and will release 2.3.1.

**Comment by Copywright** [comment] 2016-06-20 17:01
Great, leave a note here when you do! I'll remove the revert after that.

**Comment by lebedev-yury** [comment] 2016-06-20 17:20
@Copywright the issue is now fixed with version 2.3.1. Sorry for the inconvenience

**Closed** 2016-06-20 17:19 UTC
