### ISSUE TITLE
massive deprecation warning on rails 5.1

### ISSUE THREAD

**Issue by BranLiang** [lebedev-yury/carrierwave-base64#53] opened 2017-03-18 05:16 UTC
DEPRECATION WARNING: The behavior of `changed_attributes` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes.transform_values(&:first)` instead. (called from block (2 levels) in <top (required)> at /home/bran/Desktop/alexandria/spec/requests/books_spec.rb:4)
DEPRECATION WARNING: The behavior of `changes` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes` instead. (called from block (2 levels) in <top (required)> at /home/bran/Desktop/alexandria/spec/requests/books_spec.rb:4)
DEPRECATION WARNING: The behavior of `changed` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes.keys` instead. (called from block (2 levels) in <top (required)> at /home/bran/Desktop/alexandria/spec/requests/books_spec.rb:4)
DEPRECATION WARNING: The behavior of `attribute_change` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute` instead. (called from block (2 levels) in <top (required)> at /home/bran/Desktop/alexandria/spec/requests/books_spec.rb:4)
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from block (2 levels) in <top (required)> at /home/bran/Desktop/alexandria/spec/requests/books_spec.rb:4)

**Comment by Borzik** [comment] 2017-05-04 15:30
In case someone will face this issue while upgrading to Rails 5.1: it is actually caused by carrierwave gem, not this one. Using `gem 'carrierwave', '~> 1.1.0'` fixed it for me.

**Comment by lebedev-yury** [comment] 2017-05-05 07:02
@Borzik thank you! I'm closing this issue

**Closed by lebedev-yury** 2017-05-05 07:02 UTC
Labels: help wanted
