### ISSUE TITLE
Permission denied @ unlink_internal [ Windows ]

### ISSUE THREAD

**Issue by ikbalix** [lebedev-yury/carrierwave-base64#41] opened 2016-10-29 14:15 UTC
When i'm trying to upload a file i get this error im running my app on **Windows** 

```
Errno::EACCES (Permission denied @ unlink_internal - E:/Sites/project/public/uploads/tmp/1477749450-6708-0002-5051/file.jpg):

app/controllers/posts_controller.rb:57:in `block in create'
app/controllers/posts_controller.rb:56:in `create'
```

**Comment by lebedev-yury** [comment] 2016-10-30 09:30
Does this work without `carrierwave-base64`, with just using regular `carrierwave` uploaders?

**Comment by ikbalix** [comment] 2016-11-02 14:03
This problem appear when i start using `carrierwave-base64`, over think work correctly with `carrierwave` .

**Comment by lebedev-yury** [comment] 2017-02-03 10:50
@ikbalix Is this issue still relevant?

**Comment by lebedev-yury** [comment] 2017-02-07 07:22
Closing this issue for now, since I couldn't reproduce it on a VM

**Closed by lebedev-yury** 2017-02-07 07:22 UTC
